# Generated by Django 2.2 on 2019-07-06 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topbar',
            name='statement',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
