# Generated by Django 2.2.2 on 2019-06-27 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fundi', '0002_fundi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='skill',
            new_name='name',
        ),
    ]
