# Generated by Django 2.2.2 on 2019-06-27 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fundi', '0003_auto_20190627_2240'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fundi',
            old_name='Skill',
            new_name='skill',
        ),
    ]
