# Generated by Django 2.2.2 on 2019-06-27 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fundi', '0004_auto_20190627_2244'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Skill',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='fundi',
            old_name='skill',
            new_name='category',
        ),
    ]
