# Generated by Django 2.2.2 on 2019-06-28 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fundi', '0007_auto_20190627_2253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fundi',
            name='category',
        ),
    ]
